name: com.example.simple_cubit_app
description: A simple Flutter application that uses the Cubit pattern for state management to toggle text between 'Cat' (with clock icon) and 'Dog' (with person icon) on user interaction.
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  bloc: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.2.1

flutter:
  uses-material-design: true